Update README.md
AttributeError: module ‘openai’ has no attribute ‘error’

the new version remove error namespace.
need to assign old version of openai.